service: erizonEncina-ejercicioSls

frameworkVersion: ^2.59.0

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

resources:
  # Create Client
  - ${file(create-client/sls/dynamodb.yml)}
  - ${file(create-client/sls/sns.yml)}
  # Create Card
  - ${file(create-card/sls/sqs.yml)}
  # Assign gift
  - ${file(assign-gift/sls/sqs.yml)}

functions:
  - ${file(create-client/sls/serverless.yml)}
  - ${file(create-card/sls/serverless.yml)}
  - ${file(assign-gift/sls/serverless.yml)}