createCard:
  handler: src/card/handler/create.handler
  description: 'Create client card'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: dynamodb:UpdateItem    
      Resource: !GetAtt ClientTable.Arn
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - CreateCardQueue
            - Arn
