Resources:
  AssignGiftQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: integrador-erizonEncina-assignGiftQueue
  AssignGiftQueueSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref ClientCreatedTopic
      Endpoint: !GetAtt AssignGiftQueue.Arn
      Protocol: sqs
  AssignGiftQueuePolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - { Ref: AssignGiftQueue }
      PolicyDocument: 
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "SQS:SendMessage"
            Principal:
              Service: "sns.amazonaws.com"
            Resource:
              - !GetAtt AssignGiftQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Ref ClientCreatedTopic