createClient:
  handler: src/client/handler/create.handler
  description: 'Create new Client'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: SNS:Publish     
      Resource: { Ref: ClientCreatedTopic }
    - Effect: "Allow"        
      Action: dynamodb:PutItem    
      Resource: !GetAtt ClientTable.Arn
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
    CLIENT_CREATED_TOPIC_ARN: { Ref: ClientCreatedTopic }
  events:
    - http:
        path: /clients
        method: post
getClients:
  handler: src/client/handler/all.handler
  description: 'Index of Client Resource'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: dynamodb:Scan    
      Resource: !GetAtt ClientTable.Arn
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
  events:
    - http:
        path: /clients
        method: get
getClient:
  handler: src/client/handler/read.handler
  description: 'Get specific client'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: dynamodb:GetItem   
      Resource: !GetAtt ClientTable.Arn
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
  events:
    - http:
        path: /clients/get-by-id
        method: get
updateClient:
  handler: src/client/handler/update.handler
  description: 'Update specific client'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: dynamodb:UpdateItem   
      Resource: !GetAtt ClientTable.Arn
    - Effect: "Allow"        
      Action: dynamodb:GetItem   
      Resource: !GetAtt ClientTable.Arn
    - Effect: "Allow"        
      Action: SNS:Publish     
      Resource: { Ref: ClientBirthdayUpdatedTopic }
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
    CLIENT_BIRTHDAY_UPDATED_TOPIC_ARN: { Ref: ClientBirthdayUpdatedTopic }
  events:
    - http:
        path: /clients
        method: put
