createClient:
  handler: src/client/handler/create.handler
  description: 'Create new Client'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: SNS:Publish     
      Resource: { Ref: ClientCreatedTopic }
    - Effect: "Allow"        
      Action: dynamodb:PutItem    
      Resource: !GetAtt ClientTable.Arn
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
    CLIENT_CREATED_TOPIC_ARN: { Ref: ClientCreatedTopic }
  events:
    - http:
        path: /clients
        method: post
getClients:
  handler: src/client/handler/all.handler
  description: 'Index of Client Resource'
  iamRoleStatements:
    - Effect: "Allow"        
      Action: dynamodb:Scan    
      Resource: !GetAtt ClientTable.Arn
  environment:
    CLIENT_TABLE: { Ref: ClientTable }
    DEFAULT_REGION: !Sub ${AWS::Region}
    CLIENT_CREATED_TOPIC_ARN: { Ref: ClientCreatedTopic }
  events:
    - http:
        path: /clients
        method: get
